version: "2"

services:

  db:
    image: mattermost/mattermost-prod-db
    restart: unless-stopped
    volumes:
      - mattermost_db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mattermost_user
      - POSTGRES_PASSWORD=mattermost_db_password
      - POSTGRES_DB=mattermost_db

  app:
    image: mattermost/mattermost-prod-app
    restart: unless-stopped
    volumes:
      - mattermost_config:/mattermost/config:rw
      - mattermost_data:/mattermost/data:rw
      - mattermost_logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_HOST=db
      - MM_USERNAME=mattermost_user
      - MM_PASSWORD=mattermost_db_password
      - MM_DBNAME=mattermost_db


  web:
    image: mattermost/mattermost-prod-web
    expose:
      - "80"
      - "443"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.domain=${domain}
      - traefik.frontend.rule=Host:${domain}
      - traefik.port=80

volumes:
  mattermost_db:
    driver: local
  mattermost_data:
    driver: local
  mattermost_config:
    driver: local
  mattermost_logs:
    driver: local
