version: '2'
catalog:
  name: mattermost template
  version: 1.0.0
  description: a mattermost template
  # minimum_rancher_version: # The minimum version of Rancher that supports the template, v1.0.1 and 1.0.1 are acceptable inputs
  # maximum_rancher_version: # The maximum version of Rancher that supports the template, v1.0.1 and 1.0.1 are acceptable inputs
  # upgrade_from: # The previous versions that this template can be upgraded from
  questions: #Used to request user input for configuration options
    - variable: domain
      label: Domain
      description: |
        The Domain used
      default: matters.syntro.ch
      required: true
      type: string
